<SALES_ORDERS>
<ORDER_SLIP DBOP="INS">
<NUMBER>{{$oder->code}}</NUMBER>
<DATE>30.03.2024</DATE>
<TIME>08:35</TIME>
<ARP_CODE>M005</ARP_CODE>
<TOTAL_DISCOUNTED>1000</TOTAL_DISCOUNTED>
<TOTAL_VAT>180</TOTAL_VAT>
<TOTAL_GROSS>1000</TOTAL_GROSS>
<TOTAL_NET>1180</TOTAL_NET>
<RC_RATE>1</RC_RATE>
<RC_NET>1180</RC_NET>
<ORDER_STATUS>1</ORDER_STATUS>
<CREATED_BY>1</CREATED_BY>
<DATE_CREATED>30.03.2024</DATE_CREATED>
<HOUR_CREATED>8</HOUR_CREATED>
<MIN_CREATED>35</MIN_CREATED>
<SEC_CREATED>30</SEC_CREATED>
<CURRSEL_TOTAL>2</CURRSEL_TOTAL>
<DATA_REFERENCE>1</DATA_REFERENCE>
<TRANSACTIONS>
<TRANSACTION>
<TYPE>0</TYPE>
<MASTER_CODE>TM0004</MASTER_CODE>
<QUANTITY>20</QUANTITY>
<PRICE>50</PRICE>
<TOTAL>1000</TOTAL>
<VAT_RATE>18</VAT_RATE>
<VAT_AMOUNT>180</VAT_AMOUNT>
<VAT_BASE>1000</VAT_BASE>
<UNIT_CODE>ADET</UNIT_CODE>
<UNIT_CONV1>1</UNIT_CONV1>
<UNIT_CONV2>1</UNIT_CONV2>
<DUE_DATE>30.03.2024</DUE_DATE>
<CURR_PRICE>160</CURR_PRICE>
<PC_PRICE>50</PC_PRICE>
<RC_XRATE>1</RC_XRATE>
<TOTAL_NET>1000</TOTAL_NET>
<DATA_REFERENCE>1</DATA_REFERENCE>
<DETAILS> </DETAILS>
<CAMPAIGN_INFOS>
<CAMPAIGN_INFO> </CAMPAIGN_INFO>
</CAMPAIGN_INFOS>
<DEFNFLDS> </DEFNFLDS>
<PRCLISTREF>7</PRCLISTREF>
</TRANSACTION>
</TRANSACTIONS>
<ORGLOGOID/>
<DEFNFLDSLIST> </DEFNFLDSLIST>
<AFFECT_RISK>0</AFFECT_RISK>
</ORDER_SLIP>
</SALES_ORDERS>